### ISSUE TITLE
Error loading jailbreakd

### ISSUE THREAD

**Issue by theketans** [pwned4ever/Th0r_Freya#16]
i always get error loading jailbreakd during jailbreak process, if successful jailbreak with log like that but i can't use cydia
condition of this bug in iphone 6 ios 12.5.6
![IMG-20221228-WA0002](https://user-images.githubusercontent.com/50024879/209708220-62991747-5610-42ef-825b-c4980f736503.jpg)

**Comment by theketans** [comment]
and what happens when rebooting cydia becomes like this

![IMG-20221228-WA0003](https://user-images.githubusercontent.com/50024879/209711382-16d03567-7095-4695-80b9-67ee3ff0b6d9.jpg)

**Comment by pwned4ever** [comment]
Remove and retry from fresh

Sent from my iPhone

On Dec 27, 2022, at 2:02 PM, Cleverior ***@***.***> wrote:

﻿

and what happens when rebooting cydia becomes like this

[IMG-20221228-WA0003]<https://user-images.githubusercontent.com/50024879/209711382-16d03567-7095-4695-80b9-67ee3ff0b6d9.jpg>

**Comment by pwned4ever** [comment]
I'll double try my iPhone 6 12.5.6 and if I never get this error. I'd suggest wiping out the device and start over

Sent from my iPhone

On Dec 27, 2022, at 1:34 PM, theketans ***@***.***> wrote:

﻿

i always get error loading jailbreakd during jailbreak process, if successful jailbreak with log like that but i can't use cydia
condition of this bug in iphone 6 ios 12.5.6
[IMG-20221228-WA0002]<https://user-images.githubusercontent.com/50024879/209708220-62991747-5610-42ef-825b-c4980f736503.jpg>

**Comment by pwned4ever** [comment]
Please try 1.2.7 and lmk if any changes?

Sent from my iPhone

On Dec 27, 2022, at 11:51 PM, marcel c ***@***.***> wrote:

﻿ Remove and retry from fresh

Sent from my iPhone

On Dec 27, 2022, at 2:02 PM, Cleverior ***@***.***> wrote:

﻿

and what happens when rebooting cydia becomes like this

[IMG-20221228-WA0003]<https://user-images.githubusercontent.com/50024879/209711382-16d03567-7095-4695-80b9-67ee3ff0b6d9.jpg>

**Comment by pwned4ever** [comment]
I Believe this has been resolved. If any further arises please reopen a new issue
