### ISSUE TITLE
IPAD Mini 3 - 12.5.6 

### ISSUE THREAD

**Issue by github1111111111111111111111** [pwned4ever/Th0r_Freya#4]
process quits every time on  " Finding Offsets " device reboots and every time same error

**Comment by pwned4ever** [comment]
That's a bug I've noticed also. Not sure the root cause of that. However, that means that the jailbreak worked once. And the next run when it tries to extract the bootstrap it panics. Click settings, turn on restore rootfs. Remove the jailbreak and start over again. When it succeeds to remove. It needs to succeed 2 times after that from a fresh start. First success is the snapshot renaming. The second success, installs cydia

**Comment by Loukat** [comment]
Comment télécharger l’application freya svp j’ai besoin de sa

**Comment by pwned4ever** [comment]
I Believe this has been resolved. If any further arises please reopen a new issue
